### ISSUE TITLE
引入组件后报错

### ISSUE THREAD

**Issue by xielian521huacheng** [hujiulong/vue-3d-model#449]
控制台报错
       Uncaught TypeError: Cannot read properties of undefined (reading 'extend')
    at Module.fb15 (index.js?0f10:12:1)
    at __nested_webpack_require_950__ (bootstrap?c733:19:1)
    at eval (bootstrap?c733:83:1)
    at eval (bootstrap?c733:83:1)
    at webpackUniversalModuleDefinition (universalModuleDefinition?8621:1:1)
    at eval (universalModuleDefinition?8621:1:1)
    at Object../node_modules/vue-3d-model/dist/vue-3d-model.umd.js (chunk-vendors.js:127:1)
    at __webpack_require__ (app.js:113:33)
    at fn (app.js:347:21)
    at eval (index.js??clonedRuleSet-40.use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[0]!./src/App.vue?vue&type=script&lang=js:2:70)

**Comment by xjown** [comment]
我也是

**Comment by n1ch0la5** [comment]
Same issue here: 
app.js:775 Uncaught TypeError: Cannot read property 'extend' of undefined

 using Vue3 script setup

**Comment by guolixun** [comment]
+1

**Comment by greysonkk** [comment]
+1

**Comment by greysonkk** [comment]
+1 how to solve it?

**Comment by ZhuRuiHeng** [comment]
+1

**Comment by geshichuangdi** [comment]
> Same issue here: app.js:775 Uncaught TypeError: Cannot read property 'extend' of undefined
> 
> using Vue3 script setup

pardon, could you be more specifically? so poor my tech, thanks

**Comment by magicmayu** [comment]
same issue
someone knows how to solve?

**Comment by 54mu3l** [comment]
Duplicate of https://github.com/hujiulong/vue-3d-model/issues/460
