### ISSUE TITLE
使用vue3出现TypeError: Cannot read properties of undefined (reading 'extend')问题，如何解决？

### ISSUE THREAD

**Issue by greysonkk** [hujiulong/vue-3d-model#460]
![image](https://user-images.githubusercontent.com/117496665/200098417-41df0190-486d-4d67-b846-a307a3d6d189.png)

**Comment by bgitfk** [comment]
我也出现了这个bug...

**Comment by Marianna-Ma** [comment]
我也是。。。。

**Comment by 1242174973** [comment]
怎么解决了

**Comment by bgitfk** [comment]
没解决，用别的插件了 v-3d-loader

**Comment by LXMsaal** [comment]
插件版本升到2

**Comment by geshichuangdi** [comment]
> 插件版本升到2

什么意思?

**Comment by LXMsaal** [comment]
> 

![image](https://user-images.githubusercontent.com/91644514/212077971-2cf08bde-e435-4fcf-8bd1-f3de429d2653.png)

**Comment by LXMsaal** [comment]
> > 插件版本升到2
> 
> 什么意思?

![image](https://user-images.githubusercontent.com/91644514/212079536-924423ca-97f6-4742-a6e6-6469fc42eb4e.png)

**Comment by 54mu3l** [comment]
I've the same error.

```
TypeError: Cannot read properties of undefined (reading 'extend')
    at Module.fb15 (vue-3d-model.umd.js:78116:1)
    at __nested_webpack_require_658__ (vue-3d-model.umd.js:30:1)
    at eval (vue-3d-model.umd.js:94:1)
    at eval (vue-3d-model.umd.js:97:1)
    at webpackUniversalModuleDefinition (vue-3d-model.umd.js:3:1)
    at eval (vue-3d-model.umd.js:10:1)
    at ./node_modules/vue-3d-model/dist/vue-3d-model.umd.js (vendor.js:6235:1)
    at __webpack_require__ (app.js:1684:33)
    at fn (app.js:1985:21)
    at eval (index.js??clonedRuleSet-2.use[0]!./node_modules/@quasar/app-webpack/lib/webpack/loader.vue.auto-import-quasar.js??ruleSet[0].use[0]!./node_modules/vue-loader/dist/index.js??ruleSet[0].use[1]!./src/pages/XXXXXXXX.vue?vue&type=script&lang=js:13:70)
t
```

I'm using _vue 3.2.45_

**Comment by bete7512** [comment]
The same problem here.

**Comment by NewNameArk** [comment]
升级到2也没好使

**Comment by xudingxie** [comment]
使用npm指定版本安装。如果不指定版本，会自动选择1.*.*的版本。  哪怕再package.json中指定了版本，在package-lock.json中依旧是旧版本，使用npm update vue-3d-model之后发现依旧锁定旧版本。因此需要指定此版本
```cmd
npm install vue-3d-model@v2.0.0-alpha.4 --save  
```

**Comment by dragonzoebai** [comment]
不指定版本的时候默认安装的是1版本，1版本只支持vue2。在vue3中需要显示指定2版本，npm install vue-3d-model@v2.0.0-alpha.4 --save

**Comment by tsrdzy** [comment]
升级后要删除缓存文件,比如vite+vue项目要找到node_modules然后删掉里面的.vite文件夹,再重启项目.
